---
title: "Homework5"
author: "Jonathan Hernandez"
date: "September 21, 2018"
output: pdf_document
---

## Homework 5

### Choose independently two numbers B and C at random from the interval [0, 1] with

### uniform density. Prove that B and C are proper probability distributions. Note that 

### the point (B,C) is then chosen at random in the unit square.

B and C are valid probability distributions

- The area under the unit square is 1

- P(B) and P(C) $\geq$ 0 for all B and C (B and C are bounded from [0,1])

Find the probability that 

a) B + C < 1/2

B and C are continous random variables so we'll use integrals for these questions

B + C < 1/2 is computing $P(0 \leq B + C \leq 1/2)$ That is the lower half portion of 

the rectangle and the integral to solve is $\int_{0}^{1/2}\int_{0}^{1} B + C \,dB\,dC$

Solving the first integral gives

\[
\begin{aligned}
  \int_{0}^{1/2} \bigg[B^2/2 + BC \bigg]_{0}^{1} dC = \int_{0}^{1/2} 1/2 + C \,dC = \\ 
  \bigg[C/2 + C^2/2\bigg]_{0}^{1/2} = 1/4 + 1/8 = 3/8 = 0.375
\end{aligned}
\]

- This means that when B and C are picked at random, about 37.5% of time, the sum

of B and C will be within the lower half of the rectangle.

b) Find the probability that BC < 1/2

- Again using integrals and the definition of the probability density function

goal is to compute $P(0 \leq BC \leq 1/2)$ that is compute 

$\int_{0}^{1/2}\int_{0}^{1} BC \,dB\,dC$

that is 

\[
\begin{aligned}
  \int_{0}^{1/2}\int_{0}^{1} BC \,dB\,dC = \\\int_{0}^{1/2} \bigg[B^2C/2 \bigg]_{0}^{1} dC 
  = \int_{0}^{1/2} C/2 \,dC = \\ \bigg[C^2/4\bigg]_{0}^{1/2} = 1/16 = 0.0625
\end{aligned}
\]

- This means that when B and C are picked at random, about 6.25% of time, the product

of B and C will be within the lower half of the rectangle.

c) Find the probability that |B - C| < 1/2

- With this one, note $\int_{0}^{1} |{B - C}| \,dB = \bigg[((B-C)|B-C|)/2\bigg]_{0}^{1}$

which is $(2C^2 - 2C + 1) / 2$ when you evaluate the limits. Another thing to note is that

|1-C| for C [0,1] always give a positive value which is the same result of 1-C and

|-C| is just C for all C.

Solving the integral $\int_{0}^{1/2}\int_{0}^{1} |{B - C}| \,dB\,dC =$ 

\[
\begin{aligned}
  1/2\int_{0}^{1/2}(2C^2 - 2C + 1) \,dC = 1/2 \bigg[2C^3/3 - C^2 + C \bigg]_{0}^{1}
  \\ = 1/2 \bigg[1/12 - 1/4 + 1/2 \bigg] = 1/6 = 0.16666
\end{aligned}
\]

- About 16.6% of the time, taking the difference of B and C and computing their 

absolute value the result is within the lower part of the box.

d) Find the Probability of max(B,C) < 1/2

- Let's note the max function; max(B,C) = {B if B $\geq$ C and C otherwise}

Computing the integral for max(B,C) results in two possibilities:

- if max is B, $\int max(B,C) dB = \int B dB = B^2/2 + constant$

- if max is C, $\int max(B,C) dB = \int C dB = BC + constant$

- now let us solve:

Case 1: max(B,C) = B

\[
\begin{aligned}
  \int_{0}^{1/2} \int_{0}^{1} B \,dB \,dC = \\
  \int_{0}^{1/2} \bigg[B^2/2 \bigg]_{0}^{1} \,dC = \int_{0}^{1/2} 1/2 \,dC = \\
  \bigg[ C/2  \bigg]_{0}^{1/2} = 1/4 = 0.25
\end{aligned}
\]

- Case 2: max(B,C) = C

\[
\begin{aligned}
  \int_{0}^{1/2} \int_{0}^{1} C \,dB \,dC = \\
  \int_{0}^{1/2} \bigg[BC \bigg]_{0}^{1} \,dC = \int_{0}^{1/2} C \,dC = \\
  \bigg[ C^2/2  \bigg]_{0}^{1/2} = 1/8 = 0.125
\end{aligned}
\]

- We see that there is a higher chance of B and C landing on the square if we compute

the max of B and C and B is larger.

e) Find the probability of min(B,C) < 1/2

- This is the same as comptuting the integral of a min(B,C) function doing both

cases results in the same computation and answer as d)